services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: piffle
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  app:
    build: ./app
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: piffle
    ports:
    - "8501:8501"
    volumes:
      - ./app:/app
    command: streamlit run main.py --server.port=8501 --server.headless=true
volumes:
  pgdata:
